version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: labchatdb
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  postgres-test:
    image: postgres:latest
    container_name: labchatdb-test
    restart: always
    environment:
      POSTGRES_USER: ${TEST_DB_USER:-${DB_USER}}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD:-${DB_PASSWORD}}
      POSTGRES_DB: ${TEST_DB_NAME:-${DB_NAME}_test}
    ports:
      - "5433:5432"
    volumes:
      - postgres-test-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  postgres-test-data: